### ISSUE TITLE
Error when training the DNCNN

### ISSUE THREAD

**Issue by uzair789** [tum-vision/learn_prox_ops#3]
I tried to train the model by running the command

       python3 src/tf_solver.py --sigma_noise 0.02 --batch_size 128 --network DNCNN --channels 1 --pipeline bsds500 --device_name /gpu:0 --train_epochs 100

But I received an error

    Traceback (most recent call last):
         File "src/tf_solver.py", line 326, in <module>
              main()
         File "src/tf_solver.py", line 322, in main
              solver = Solver()
         File "src/tf_solver.py", line 120, in __init__
              pipelines = PIPELINES[opt.pipelines](opt, test_epochs=None)
         File "/home/uzair/Denoising_Raeid/learn_prox_ops/src/data.py", line 143, in __init__
               opt.train_epochs)
         File "/home/uzair/Denoising_Raeid/learn_prox_ops/src/data.py", line 239, in tf_data_pipeline
               min_after_dequeue=min_after_dequeue)
         File "/home/uzair/Denoising_Raeid/learn_prox_ops/src/utilities.py", line 291, in 
                 tf_shuffle_batch_join
                tensor_list_list, enqueue_many)
          TypeError: _store_sparse_tensors_join() missing 1 required positional argument: 'keep_input'

How can I fix this? Thanks

**Comment by timmeinhardt** [comment]
I reproduced the error and there seems to be a problem with the TensorFlow version. I will try to fix it but until then I can highly recommend [this](https://github.com/crisb-DUT/DnCNN-tensorflow) repository. Which includes a more recent DnCNN reimplementation with scores closer to the original paper.
